import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiCube,
  HiServer,
  HiShieldCheck,
  HiCubeTransparent,
  HiSquare3Stack3D,
  HiCodeBracket,
  HiCircleStack,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiNotion,
  SiJira,
  SiSpring,
  SiPython,
  SiDjango,
  SiReact,
  SiFlutter,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiOracle,
  SiDocker,
  SiGit,
  SiPostman,
  SiSlack,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaBehance } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  notion: SiNotion,
  jira: SiJira,
  box: HiCube,
  java: HiCodeBracket,
  spring: SiSpring,
  python: SiPython,
  django: SiDjango,
  react: SiReact,
  flutter: SiFlutter,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  sqlserver: HiCircleStack,
  sqlite: SiSqlite,
  oracle: SiOracle,
  docker: SiDocker,
  git: SiGit,
  postman: SiPostman,
  slack: SiSlack,
  api: HiServer,
  security: HiShieldCheck,
  architecture: HiCubeTransparent,
  microservices: HiSquare3Stack3D,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  behance: FaBehance,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
